- name: Collecting Facts
  hosts: local
  # become: yes
  become_user: deployer
  become_method: sudo
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  # become: yes
  become_user: deployer
  become_method: sudo
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - python
    # - node
    # - ruby
    # - hub
    - rg
    - exa
    # - bat
    - tmux
    # - git-flow
    - fzf
    - kubernetes
    # - jrnl
    - {role: macos, when: ansible_os_family == "Darwin"}
