- name: Collecting Facts
  hosts: local
  become_user: deployer
  become_method: sudo
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  become_user: deployer
  become_method: sudo
  roles:
    - {role: zsh, tags: ['bootstrap']}
