syntax on
set ic
set number

set backspace=indent,eol,start " backspace over everything in insert mode "
set tabstop=2 shiftwidth=2 expandtab

""" BASE CUSTOMIZATIONS """
" NOTE: Many base customizations come from vim-sensible and vim-opinion "
set encoding=utf-8
set relativenumber
set autoread " reload files when changed on disk, i.e. via `git checkout` "
set clipboard^=unnamedplus,unnamed " Make "yanks" work with system clipboard "

" Indents "
set autoindent
set expandtab " expand tabs by default (overloadable per file type later) "
set tabstop=4 softtabstop=4 shiftwidth=4
set shiftround " use multiple of shiftwidth when indenting with '<' and '>' "

" No bells "
set noerrorbells visualbell t_vb=

""" VISUAL SETTINGS """
if &term =~ '256color' | set t_ut= | endif
" NOTE: colorscheme will be set by night-and-day. This will only "
" be in effect if night-and-day is disabled "
set background=dark

" Show trailing whitespace "
set list listchars=tab:▸\ ,trail:▫

set cursorline  " have a line indicate cursor location "
set previewheight=25  " Larger preview height "

" Set minimum window size to 79x5. "
set winwidth=79 winheight=5 winminheight=5

" Patterns to ignore for expand(), ctrlp, etc. "
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz,*.swp,*~,._*,*.pyc,*__pycache__*,*.egg-info

" Persistent undo (can use undos after exiting and restarting) "
if exists("+undofile")
  if isdirectory($HOME . '/.vim/undo') == 0
    :silent !mkdir -p ~/.vim/undo > /dev/null 2>&1
  endif
  set undodir=./.vim-undo// undodir+=~/.vim/undo// undofile
endif


augroup configgroup
  autocmd!
  " Make sure Vim returns to the same line when you reopen a file. "
  autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | execute 'normal! g`"zvzz' | endif

  " Automatically adjust quickfix window depending on how much text there is "
  autocmd FileType qf call AdjustWindowHeight(3, 20)
  function! AdjustWindowHeight(minheight, maxheight)
    exe max([min([line("$"), a:maxheight]), a:minheight]) . "wincmd _"
  endfunction

  """ Languages """
  " prose (hard wrap and autoformat paragraphs) "
  autocmd BufRead,BufNewFile jrnl*.txt,editor*.txt set filetype=markdown
  autocmd BufRead,BufNewFile jrnl*.txt,editor*.txt,*.md,*.rst setlocal nolist formatoptions+=ntl textwidth=72 wrapmargin=0
  autocmd BufRead,BufNewFile .eslintrc set filetype=json
  " commit messages "
  autocmd Filetype gitcommit setlocal nolist textwidth=72
augroup END

" GUI settings, e.g. MacVim "
set guifont=Ubuntu\ Mono:h14
" Hide scrollbars and menu "
set guioptions-=T guioptions-=R guioptions-=r guioptions-=m guioptions-=l guioptions-=L
